package:
  name: pygenn
  version: "0.0.0"  # Will be overridden by version.txt in setup.py

source:
  git_url: https://github.com/genn-team/genn.git
  git_rev: master  # or replace with a tag v5.2.0

build:
  number: 0
  script_env:
    - CUDA_PATH
  script: |
    export CUDA_PATH="${BUILD_PREFIX}"
    $PYTHON setup.py install --single-version-externally-managed --record=record.txt
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
    - python
    - setuptools
    - pip
    - wheel
    - pybind11
    - psutil
    - wget #To get CUDA installations 
    - pkg-config
    - cudatoolkit-dev 11.7  # nvcc and cuda headers

  host:
    - python
    - numpy
    - psutil
    - pybind11 

  run:
    - python
    - numpy
    - psutil
    - cudatoolkit 11.7 # runtime CUDA libraries
    - importlib-metadata  # [py<38]

test:
  imports:
    - pygenn

about:
  home: https://github.com/genn-team/genn
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "GeNN Python bindings (pygenn) with CUDA backend support"
  description: |
    GeNN (GPU enhanced Neuronal Networks) is a code generation framework for
    accelerating spiking neural network simulations using GPUs.
    This package provides the Python bindings to use GeNN in Python.
  dev_url: https://github.com/genn-team/genn

extra:
  recipe-maintainers:
    - to-be-decided
