python:
  - 3.11

gcc:
  - 11

cuda_version:
  - 12.4

cuda_cudart:
  - 12.4
cuda_cudart_dev:
  - 12.4
cuda_nvcc:
  - 12.4
cuda_libraries:
  - 12.4
cuda_libraries_dev:
  - 12.4

zip_keys:
  - [cuda_version, cuda_cudart, cuda_cudart_dev, cuda_nvcc, cuda_libraries, cuda_libraries_dev]
